package org.flosun.ksp_processing.processors

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import org.flosun.ksp_processing.annotations.GenerateToMap

class GenerateToMapProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
) : SymbolProcessor {

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val symbols = resolver
            .getSymbolsWithAnnotation(GenerateToMap::class.qualifiedName!!)
            .filterIsInstance<KSClassDeclaration>()

        symbols.forEach { classDeclaration -> generateToMapFunction(classDeclaration) }
        return emptyList()
    }

    private fun generateToMapFunction(declaration: KSClassDeclaration) {
        val packageName = declaration.packageName.asString()
        val className = declaration.simpleName.asString()

        val fileName = "${className}ToMap"
        val file = codeGenerator.createNewFile(
            dependencies = Dependencies.ALL_FILES,
            packageName = packageName,
            fileName = fileName
        )

        file.bufferedWriter().use { writer ->
            writer.appendLine("package $packageName")
            writer.appendLine()
            writer.appendLine("// This file is generated by GenerateToMapProcessor")
            writer.appendLine("fun $className.toMap(): Map<String, Any?> {")
            writer.appendLine("    return mapOf(")
            declaration.getAllProperties().forEach { property ->
                val propName = property.simpleName.asString()
                writer.appendLine("        \"$propName\" to this.$propName,")
            }
            writer.appendLine("    )")
            writer.appendLine("}")
        }
    }
}

class GenerateToMapProcessorProvider : SymbolProcessorProvider {

    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor {
        return GenerateToMapProcessor(
            codeGenerator = environment.codeGenerator,
            logger = environment.logger,
        )
    }

}