package org.flosun.ksp_processing.processors

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import org.flosun.ksp_processing.annotations.GenerateUpdate

class GenerateUpdateFuncProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
) : SymbolProcessor {

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val symbols = resolver
            .getSymbolsWithAnnotation(GenerateUpdate::class.qualifiedName!!)
            .filterIsInstance<KSClassDeclaration>()

        symbols.forEach { classDeclaration -> generateUpdateFunction(classDeclaration) }
        return emptyList()
    }

    private fun generateUpdateFunction(declaration: KSClassDeclaration) {
        val packageName = declaration.packageName.asString()
        val className = declaration.simpleName.asString()

        val fileName = "${className}Update"
        val file = codeGenerator.createNewFile(
            dependencies = Dependencies.ALL_FILES,
            packageName = packageName,
            fileName = fileName
        )

        file.bufferedWriter().use { writer ->
            writer.appendLine("package $packageName")
            writer.appendLine()
            writer.appendLine("// This file is generated by GenerateUpdateFuncProcessor")
            writer.appendLine("fun $className.update(")
            declaration.getAllProperties().forEach { property ->
                val propName = property.simpleName.asString()
                val propType = property
                    .type
                    .resolve()
                    .declaration
                    .qualifiedName?.asString() ?: "Any"

                writer.appendLine("    $propName: $propType = this.$propName,")
            }
            writer.appendLine("): $className {")
            writer.appendLine("    return $className(")

            declaration.getAllProperties().forEach { property ->
                val propName = property.simpleName.asString()
                writer.appendLine("        $propName = $propName,")
            }

            writer.appendLine("    )")
            writer.appendLine("}")
        }
    }

}

class GenerateUpdateFuncProcessorProvider : SymbolProcessorProvider {

    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor {
        return GenerateUpdateFuncProcessor(
            codeGenerator = environment.codeGenerator,
            logger = environment.logger,
        )
    }

}